// <auto-generated />
using GoodHamburguer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburguer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425163315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("GoodHamburguer.Models.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Acompanhamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Batata Frita",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Refrigerante",
                            Preco = 2.50m
                        });
                });

            modelBuilder.Entity("GoodHamburguer.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SanduicheId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SanduicheId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GoodHamburguer.Models.Sanduiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sanduiches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "X Burguer",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "X Egg",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "X Bacon",
                            Preco = 7.00m
                        });
                });

            modelBuilder.Entity("GoodHamburguer.Models.Acompanhamento", b =>
                {
                    b.HasOne("GoodHamburguer.Models.Pedido", null)
                        .WithMany("Acompanhamento")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("GoodHamburguer.Models.Pedido", b =>
                {
                    b.HasOne("GoodHamburguer.Models.Sanduiche", "Sanduiche")
                        .WithMany()
                        .HasForeignKey("SanduicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanduiche");
                });

            modelBuilder.Entity("GoodHamburguer.Models.Pedido", b =>
                {
                    b.Navigation("Acompanhamento");
                });
#pragma warning restore 612, 618
        }
    }
}
